# Generated by Django 6.0.8 on 2026-08-09 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveBigIntegerField(verbose_name='ID do TMDB')),
                ('media_type', models.CharField(choices=[('movie', 'Filme'), ('tv', 'Série')], max_length=5, verbose_name='tipo')),
                ('name', models.CharField(max_length=255, verbose_name='título')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='título original')),
                ('poster_url', models.URLField(blank=True, max_length=500, verbose_name='URL do pôster')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='data de lançamento')),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='nota no TMDB')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'título',
                'verbose_name_plural': 'títulos',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('media_type', 'tmdb_id'), name='unique_tmdb_title_by_media_type')],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, verbose_name='visitante')),
                ('genre_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do gênero')),
                ('genre_name', models.CharField(blank=True, max_length=100, verbose_name='gênero')),
                ('min_rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='nota mínima')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sorteado em')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='movies.title', verbose_name='título')),
            ],
            options={
                'verbose_name': 'sorteio',
                'verbose_name_plural': 'sorteios',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['visitor_id', '-created_at'], name='generation_visitor_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(db_index=True, verbose_name='visitante')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='favoritado em')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='movies.title', verbose_name='título')),
            ],
            options={
                'verbose_name': 'favorito',
                'verbose_name_plural': 'favoritos',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['visitor_id', '-created_at'], name='favorite_visitor_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('visitor_id', 'title'), name='unique_favorite_per_visitor')],
            },
        ),
    ]
