# Generated by Django 6.0.8 on 2026-08-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_sharedcacheentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsAppContact',
        ),
    ]
